begriffs/haskell-vim-now

.vimrc
README.md
install.sh

Run [stylish-haskell](https://github.com/jaspervdj/stylish-haskell) on Haskell buffers every time they are saved.

Add stylish-haskell

---

.vimrc
install.sh

There are some changes being made to Vundle recently:
* The repo is renamed from _gmarik/vundle_ to _gmarik/Vundle.vim_.
* We should use the ``vundle#begin()`` / ``vundle#end()`` block in place of ``vundle#rc()``.
* _Bundle_ should be renamed to _Plugin_.
Kindly refer to [here](https://github.com/gmarik/Vundle.vim/commit/0521de95eac09298c4e71b3662839612280c1ae9), [here](https://github.com/gmarik/Vundle.vim/blob/v0.10.2/doc/vundle.txt#L372-L396) and [here](https://github.com/gmarik/Vundle.vim/issues/413) for more information.

`Bundle` is deprecated in Vundle

---

.vimrc

When using sandbox inside a project, lots of files are generated under .cabal-sandbox. This increases dramatically the loading time when using fuzzy file find. Therefore I suggest ignore this folder in fuzzy file find plugin.

ingore files under .cabal-sandbox when using fuzzy file find

---

.vimrc

Needed for certain Cygwin installations. Otherwise there is a mixture of windows and unix style in the basedir.

Fixes basedir for ghc_mod

---

.vimrc
install.sh

Installs helper binaries with Stack and automates some tasks from #72.
TODO: configure codex to look in the correct place for installed packages. The haskell-vim-now installer currently creates `~/.codex` with these settings 
```yaml
hackagePath: .cabal-sandbox/packages/
tagsFileHeader: false
tagsFileSorted: false
tagsCmd: hasktags --extendedctag --ignore-close-implementation --ctags --tags-absolute --output='\$TAGS' '\$SOURCES'
```
But this still references a cabal sandbox. I don't know the correct settings to use. It may depend on the results of https://github.com/aloiscochard/codex/issues/39

Use Stack rather than Cabal

---

git-hscope

Not strictly necessary, but using `pushd` and `popd` should be a bit more stable than plain old `cd`.

Use pushd/popd instead of cd

---

.vimrc

kien/ctrlp.vim is unmaintained and ctrplvim/ctrlp.vim should be used instead.
See kien/ctrlp.vim#669.

Switch to maintained fork of ctrlp.vim

---

.vimrc

Latest commit to sjl/Gundo dates on 11 Jul 2013. Author is not maintaining this project since then.
https://github.com/simnalamburt/vim-mundo is a fork of Gundo with fixes and a few new features (see https://github.com/simnalamburt/vim-mundo#whats-the-difference).
Besides, vim-mundo has NeoVim support (tested here, all good).

Use vim-mundo instead of Gundo

---

install.sh

Quick fix for Fedora Workstations with DNF, where Yum is installed too for compatibility.
Yum is mapped to DNF anyway, so there's no reason to repeat ourselves here.

Do not use YUM if DNF found

---

.vimrc
install.sh

Related to #81
It's necessary to change all *Plugin* to *Plug* in *bundles.vim*, so I decided to (temporary at least) change source from *bundles.vim* to *plug.vim* to avoid errors.
It can be done automatically via **install.sh** or manually by user (preferred, I think).

Completely replace Vundle with vim-plug

---

.gitignore
.vimrc
README.md
install.sh

* ~/.config/haskell-vim-now/ is the new project directory (DIR),
* .vimrc and .vim backups moved to DIR/backup/...,
* user configs placed to DIR/vimrc.local DIR/plugins.local,
* user now can use vimrc.local.pre to make configurations before .vimrc is executed,
* automated migration of user configs and installation (not sure i've done everything needed),
* installer now use stack to find it's configuration and bin path,
* README is correct now (vim-plug and new DIR).
The only thing you need to do is run new install.sh. It would move your installation of **haskell-vim-now** to `~/.config`, move `.vimrc.local` and `.vim.local/bundles.vim` to `~/.config/haskell-vim-now/vimrc.local` and `~/.config/haskell-vim-now/plugins.local` (**replacing Plugin directives with Plug**), then remove …

Move haskell-vim-now config files to $XDG_CONFIG_HOME/haskell-vim-now

---

install.sh
scripts/func.sh
scripts/setup.sh

install.sh is responsible for haskell-vim-now repo clone (and pull) and
should be kept as simple and short as possible. Everything else is done
in setup.sh.
Other improvements:
* Paint printed messages with red, green and yellow colors;
* Split actions in functions (install, setup);
* Stack global config is obtained with "stack path" command (not hard-
coded anymore);
* Installer now prints all missing programms, not one-by-one;
* Add checks for empty stack paths;
* Add checks for "stack setup" and "stack install" return codes;
* Don't use dumb terminal with vim-plug (it erases lines from terminal);
* Add some more messages;
General cleanups and reformating. Code is now easier to read.
Closes #105. Not complete, though. Need to split setup.sh some more (to setup.sh and update.sh). But for …

Decompose Installer

---

.gitignore
.vimrc
scripts/setup.sh

I think this is the last one, isn't it?
Now Haskell Vim Now fully uses stack-path provided paths to stack's global config and bin directory.
I've made it via additional symlink to bin path (which is the only thing required in vimrc).

No more hardcoded stack paths in Haskell Vim Now

---

.vimrc

Don't set leader if already set (presumably in vimrc.local.pre)

Don't set leader if already set

---

.vimrc

The current bindings for the Hoogle commands that require user input can include the space automatically so the user doesn't have to worry about it.

Add space to Hoogle commands where input is required.

---

.vimrc
README.md
scripts/neovim.sh
scripts/setup.sh

Add script to backup any existing neovim configuration, and symlink the HVN configuration
into ~/.config/nvim/.
Also adds some neovim specific settings into the .vimrc, wrapped in checks for
has('nvim'), so they don't affect normal vim.
This closes #87 and closes #114. Sorry for the duplicate pull request in #123.

Improved Neovim support and script to replace configs

---

README.md

This avoids that we execute arbitrary code provided by an attacker in the network

Download install script via HTTPS

---

.vimrc
scripts/setup.sh

Remove the pinned nightly Stackage snapshot, using LTS-4.2 instead.  Remove the pinned pointful and pointfree versions.  Fix issue observed in clean install on OS X where the PATH for vim gets confused.

Fixes for #142 and #143.

---

scripts/setup.sh

As of __LTS-5.2__, `pure-cdb` and `cabal-helper` are on Stackage, so we do not need to set `extra-deps` anymore.
And as a bonus I fixed incorrect path to `neovim.sh`. Now user can copy-paste and run.

Remove extra deps and fix path to neovim.sh script

---

.vimrc

Due to https://github.com/scrooloose/syntastic/commit/544acba17dbc72ca84951c29d774e317914d8a0d, it's no longer possible to use ghc-mod with syntastic.
This is initial (working) attempt to migrate to Neomake. Need some testing and tweaks.
It has some regressions:
- No error column highlight,
- :Errors = :lopen
For neovim it works asynchronously + you can run checker on file save (you don't have to wait for it to complete, just continue your work).
Closing https://github.com/begriffs/haskell-vim-now/issues/148

Replace hdevtools with ghc-mod, replace Syntastic with Neomake

---

scripts/setup.sh

Fixes a bug introduced by #163: setup script calls `stack path` before `stack setup`, which leads to setup procedure failure during first time installation.
Fixes https://github.com/begriffs/haskell-vim-now/issues/168 and https://github.com/begriffs/haskell-vim-now/issues/167.

Fix setup script

---

scripts/setup.sh

Due to latest stack's warnings:
'--local-bin-path' will be removed in a future release.
'--global-stack-root' will be removed in a future release.

Fix deprecated `stack path` options

---

scripts/setup.sh

`stack-resolver` is an incorrect name for `shell`, making installation script incompatible with shell (`sh install.sh`).

Fix syntax for shell (sh)

---

.travis.yml
README.md

Yup, it's CI, finally.
Spent quite some time to make it work..
Well, it's not almighty, this config uses cache for `.stack` and `.local/bin`, which makes it more of an upgrade testing rather than first-time-installation. Without caching every build would take forever! =)
@begriffs don't forget to activate builds @ travis-ci.org!

Add Travis-CI integration

---

.vimrc
scripts/setup.sh

Fixes #135
Sadly there is no RPM package for the `par` command that I could find so on CentOS the installer will fail and prompt the user to install it themselves. They will have to figure out how to build from source.

Fix paragraph formatting with par

---

README.md
install.sh
scripts/setup.sh

The first commit is a refactor without changing any existing functionality. I have taken care that no behavior changes unless something might have crept in inadvertently.
Other than the refactor, it adds two command line options to install.sh. One for a basic installation without Haskell components and another to specify a repo to install from. I am providing the motivation for both below.
Basic Installation: haskell vim now has pretty good common (non-haskell) settings as well. I want to use the same setup even where I do not use haskell or in setups where installing stack and GHC would take too much space and time even though I won't need them. Now, I can just provide an option to install and have the same setup elsewhere as well. Even non-haskell users can now use haskell-vim-now, …

Refactor to allow a basic setup without Haskell components

---

.vimrc
vimrc.haskell

Keep all language specific config in `vimrc.haskell`. Easier for maintenance and figuring out Haskell specific vs language independent settings. This is sort of a language specific vimrc module.

Refactor .vimrc to separate haskell specific cfg

---

scripts/setup.sh

'sed -r' command was not portable on Mac.

Fix extracting stack resolver (fixes #195)

---

install.sh
scripts/func.sh
scripts/setup.sh

This pull request has a number of fixes described below. Fixes are in logically independent commits:
1) Support macports package manager (57d0691 & 	d04b877)
2) Pass advanced install options via env vars to enable passing the options even when bash executes the script via stdin.
3) Bug fix - bash syntax error when more than one space separated items are present in a list
4) install script fails when curl is not installed, so install it via the package manager. I did this only for 'apt' as mac has curl by default and I cannot test for 'yum'.

support macports, package install bug fix, ensure curl

---

scripts/func.sh

Homebrew errors if you try to do brew install with no package arguments.
Fixes #206

Do not try to install empty list of pkgs

---

.vimrc

Closes https://github.com/begriffs/haskell-vim-now/issues/218.

Add vim-bracketed-paste to plugins.

---

scripts/setup.sh

Temporarily pinning to `hindent` to Stackage nightly `nightly-2016-12-28` to install version 5.2.1.  This is only necessary until LTS `hindent` is 5.x.x.

Ensure hindent 5 is installed by pinning version 5.2.1 (fixes #221)

---

Dockerfile

The script for installation onto linux requires the sudo application to exist when it executes. The base haskell image does not provide this command.

Install sudo application for script usage.

---

.travis.yml
dependencies.cabal
install.sh
scripts/setup.sh

Pin a few things to older LTS versions to make install from scratch less painful when using LTS-8.
~Move hindent to the main install list as it no longer requires a specific pinned nightly (Hindent 5 is in LTS-8.5).~
Call `hoogle generate` instead of `hoogle data`.

Get LTS-8.5 working

---

.travis.yml
install.sh
scripts/setup.sh

Problem was that the 'boolean' values used before were actually just an empty variable and a 'y' character. When the BASIC_ONLY parameter was passed into main, if --basic was not used then the variable was empty and so wasn't recognised as a parameter at all.
This meant that the 3rd parameter (the hoogle db one), got passed in as the second and as it was set to 'y' by default the Haskell binary installation was skipped.
I just replaced these pseudo booleans with actual booleans and it is a little bit simpler now as a result.  Then renamed the variables so that the logic made a little more sense.

Fixing install.sh so that the BASIC_ONLY option does not always skip the haskell installation.

---

.vimrc

Closes https://github.com/begriffs/haskell-vim-now/issues/223.

Use `softtabstop` instead of `tabstop`.

---

install.sh
scripts/setup_haskell.hs

Bail out of install if stack is not installed

---

install.sh

Check for a required minimum `stack` version of 1.4.0.

Fixes #258: Need to check for minimum required stack version

---

scripts/setup_haskell.hs

This PR gets the installer working again, per discussion over in #282.
Relying on lts-7.24 is a bit of a hack, but would rather get the installer working again now and we come up with a better solution later.
Special thanks to @bidhan-a!  @bidhan-a added support to selectively not bail out of the whole installer if a `stackInstall` fails and added a link for users to get more info on installing `ghc-mod` after the fact.

Temporarily rely on lts-7.24 for cabal-install and the helper binaries

---

.travis.yml
.vimrc
README.md
scripts/setup_haskell.hs
vimrc.haskell

* use [ghcide](https://github.com/digital-asset/ghcide) instead of [ghc-mod](https://github.com/DanielG/ghc-mod)
* use last LTS resolver
* don't install broken helpers
I'm not sure it is a satisfactory PR, but it it a merest attempt to renew haskell-vim-now.

an attempt to make haskell-vim-now usable with newer GHC
