- .vimrc
See https://github.com/gmarik/Vundle.vim/issues/16.
> filetype should be off before loading vundle

- .vimrc
- git-hscope
yesod + any other project using templatehaskell
> make hscope bindings work with yesod

- README.md
So we know where to look for it.
> where the backup is

- .vimrc
- README.md
A small addition on what I believe should be a minimum set of buffer commands.
> Added shortcut for C-W o to ,bo

- README.md
^
Need to check is different version of bash and curl though.
> Shot, sweet, one liner.

- README.md
@begriffs it must work fine now.
> Install command fixed.

- Dockerfile
> fix Docker installer

- .vimrc
> plugin repo moved

- install.sh
Also accomodating Stack's change from global to global-project
> Invoke sed in a cross-platform way

- Dockerfile
> Update Dockerfile to install stack

- .gitignore
- .vimrc
- README.md
- install.sh
Thanks to the suggestion of @skatenerd
> Switch from ghc-mod to hdevtools

- .vimrc
Ignore stack's work files in fuzzy project files search.
> Ignore stack work directory in fuzzy file find

- .vimrc
- install.sh
Needed to make airline look like this:
Don't know how this package is called on Mac..
> use powerline fonts for airline

- install.sh
@jacksonja would you try this on your machine and see if it works?
> Create config dir if it does not exist

- scripts/func.sh
- scripts/setup.sh
In issue #98 i noticed installer is printing incorrect return codes on errors. Now fixed.
In addition I simplified some 2-line conditions with pattern of check-print-exit and check-do to oneliners.
> Fix retcodes

- scripts/func.sh
- scripts/setup.sh
Attempt to fix cygwin installation problems. *Untested*.
Closes #98
> Add fix for windows-style paths stack-path returns

- scripts/setup.sh
9667c75 fixes #134.
20b5f02 fixes the problem I reported on #121 by means analogous to the fix of #132.
> Fix installation on Mac OS X (homebrew/dupes/make and pointfree)

- .vimrc
- README.md
- scripts/setup.sh
Closes https://github.com/begriffs/haskell-vim-now/issues/102
> Add apply-refact support via hlint-refactor-vim plugin

- scripts/setup.sh
- Prefer explicitly configured global stack resolver
- Bump default resolver to lts-5.12
> Use global stack resolver if explicitly configured

- .vimrc
Hi, 
GundoToggle is deprecated.
> Changed GundoToggle to MundoToggle

- scripts/func.sh
- scripts/setup.sh
* Make variables local to function (setup.sh).
* Use stackage latest LTS by default or fallback to user's one.
* Extract `stack install` list of packages to the `STACK_LIST` variable.
* Remove info messages from `stack_resolver` function.
* Remove `hdevtools` from `STACK_LIST`.
* Small refactorings (move "Aborting..." to `exit_err`, add `exit_err_report` function).
Accept this after `travis` PR to let it test these changes. ;)
> Some small fixes and refactorings

- README.md
> Add HVN replacing user's configs warning to README

- README.md
> Do not encourage piping to bash

- .travis.yml
- scripts/setup.sh
I added Mac tests along with Linux on Travis. Linux works OK but Mac hangs when running vim-plug. Any ideas?
Fixes #199
Also specifying a particular version of `codex` and some of its dependencies feels remarkably janky. We could choose another LTS version when installing helper binaries but that might cause a whole new GHC to be pulled down and compiled which would increase install time. Also building ghc-mod under a different version than the developer is likely to use would probably make it break on actual projects (it's finicky).
> Build on LTS-7

- install.sh
Closes https://github.com/begriffs/haskell-vim-now/issues/213.
> Add option to force sync on updates.

- README.md
- install.sh
When testing pull requests it's nice to be able to specify the desired branch of a fork to install.
> Allow branch override during clone

- scripts/setup_haskell.hs
Fixes #270
There is no significant advantage of choosing a resolver. However, there
are significant disadvantages:
1) The cabal-install version installed using default resolver may
mismatch with the chosen resolver and therefore stack solver itself may
fail. See issue #270.
2) A different resolver may take more space and pollute the users'
.stack with more snapshots.
Therefore we solve using the user's resolver and use the same to
install.
I added a few "XXX" in the code where it can be improved.
This works well with lts-9.13, however as I suggested in one of the fixup comments in the code for best results we should solve for each helper bin independently so that we do not have conflicting deps and therefore avoid the failure of solver.
> Use default resolver to solve for and install helper bins

- README.md
- install.sh
I've been able to solve the issue #284 
`$ ./install.sh --nix --repo git@github.com:p-alik/haskell-vim-now.git`
> installer support --nix parameter to be able running stack in nix-shell
